// This file was generated by Mendix Studio Pro.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package nanoflowcommons.proxies;

public enum GeocodingProvider
{
	Google("f703cd8a-278e-4d35-a759-6ab8c6747c2a"),
	Geocodio("aa0021ba-6bb5-4b9f-8e9b-f181f17e67b2"),
	LocationIQ("969b22b9-7b9e-4848-ad9e-4dbc0cde9c29"),
	MapQuest("9a90cf95-9d6d-4901-8b65-7ee2f7dd2010");

	private final java.lang.String i18nCaptionKey;
	
	private GeocodingProvider(java.lang.String i18nCaptionKey)
	{
		this.i18nCaptionKey = i18nCaptionKey;
	}

	public java.lang.String getCaption(java.lang.String languageCode)
	{
		String caption = com.mendix.core.Core.getInternationalizedString(languageCode, i18nCaptionKey);
		return caption.isEmpty() ? getCaption() : caption;
	}

	public java.lang.String getCaption()
	{
		return com.mendix.core.Core.getInternationalizedString("en_US", i18nCaptionKey);
	}
}
