// This file was generated by Mendix Studio Pro.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package system.proxies;

public class ConsumedODataConfiguration implements com.mendix.systemwideinterfaces.core.IEntityProxy
{
	private final com.mendix.systemwideinterfaces.core.IMendixObject consumedODataConfigurationMendixObject;

	private final com.mendix.systemwideinterfaces.core.IContext context;

	/**
	 * Internal name of this entity
	 */
	public static final java.lang.String entityName = "System.ConsumedODataConfiguration";

	/**
	 * Enum describing members of this entity
	 */
	public enum MemberNames
	{
		ServiceUrl("ServiceUrl"),
		ProxyConfiguration("ProxyConfiguration"),
		ProxyHost("ProxyHost"),
		ProxyPort("ProxyPort"),
		ProxyUsername("ProxyUsername"),
		ProxyPassword("ProxyPassword");

		private final java.lang.String metaName;

		MemberNames(java.lang.String s)
		{
			metaName = s;
		}

		@java.lang.Override
		public java.lang.String toString()
		{
			return metaName;
		}
	}

	public ConsumedODataConfiguration(com.mendix.systemwideinterfaces.core.IContext context)
	{
		this(context, com.mendix.core.Core.instantiate(context, entityName));
	}

	protected ConsumedODataConfiguration(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject consumedODataConfigurationMendixObject)
	{
		if (consumedODataConfigurationMendixObject == null) {
			throw new java.lang.IllegalArgumentException("The given object cannot be null.");
		}
		if (!consumedODataConfigurationMendixObject.isInstanceOf(entityName)) {
			throw new java.lang.IllegalArgumentException(String.format("The given object is not a %s", entityName));
		}	

		this.consumedODataConfigurationMendixObject = consumedODataConfigurationMendixObject;
		this.context = context;
	}

	/**
	 * Initialize a proxy using context (recommended). This context will be used for security checking when the get- and set-methods without context parameters are called.
	 * The get- and set-methods with context parameter should be used when for instance sudo access is necessary (IContext.createSudoClone() can be used to obtain sudo access).
	 * @param context The context to be used
	 * @param mendixObject The Mendix object for the new instance
	 * @return a new instance of this proxy class
	 */
	public static system.proxies.ConsumedODataConfiguration initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject mendixObject)
	{
		return new system.proxies.ConsumedODataConfiguration(context, mendixObject);
	}

	public static system.proxies.ConsumedODataConfiguration load(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		com.mendix.systemwideinterfaces.core.IMendixObject mendixObject = com.mendix.core.Core.retrieveId(context, mendixIdentifier);
		return system.proxies.ConsumedODataConfiguration.initialize(context, mendixObject);
	}

	/**
	 * @return value of ServiceUrl
	 */
	public final java.lang.String getServiceUrl()
	{
		return getServiceUrl(getContext());
	}

	/**
	 * @param context
	 * @return value of ServiceUrl
	 */
	public final java.lang.String getServiceUrl(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.ServiceUrl.toString());
	}

	/**
	 * Set value of ServiceUrl
	 * @param serviceurl
	 */
	public final void setServiceUrl(java.lang.String serviceurl)
	{
		setServiceUrl(getContext(), serviceurl);
	}

	/**
	 * Set value of ServiceUrl
	 * @param context
	 * @param serviceurl
	 */
	public final void setServiceUrl(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String serviceurl)
	{
		getMendixObject().setValue(context, MemberNames.ServiceUrl.toString(), serviceurl);
	}

	/**
	 * Get value of ProxyConfiguration
	 * @param proxyconfiguration
	 */
	public final system.proxies.ProxyConfiguration getProxyConfiguration()
	{
		return getProxyConfiguration(getContext());
	}

	/**
	 * @param context
	 * @return value of ProxyConfiguration
	 */
	public final system.proxies.ProxyConfiguration getProxyConfiguration(com.mendix.systemwideinterfaces.core.IContext context)
	{
		Object obj = getMendixObject().getValue(context, MemberNames.ProxyConfiguration.toString());
		if (obj == null) {
			return null;
		}
		return system.proxies.ProxyConfiguration.valueOf((java.lang.String) obj);
	}

	/**
	 * Set value of ProxyConfiguration
	 * @param proxyconfiguration
	 */
	public final void setProxyConfiguration(system.proxies.ProxyConfiguration proxyconfiguration)
	{
		setProxyConfiguration(getContext(), proxyconfiguration);
	}

	/**
	 * Set value of ProxyConfiguration
	 * @param context
	 * @param proxyconfiguration
	 */
	public final void setProxyConfiguration(com.mendix.systemwideinterfaces.core.IContext context, system.proxies.ProxyConfiguration proxyconfiguration)
	{
		if (proxyconfiguration != null) {
			getMendixObject().setValue(context, MemberNames.ProxyConfiguration.toString(), proxyconfiguration.toString());
		} else {
			getMendixObject().setValue(context, MemberNames.ProxyConfiguration.toString(), null);
		}
	}

	/**
	 * @return value of ProxyHost
	 */
	public final java.lang.String getProxyHost()
	{
		return getProxyHost(getContext());
	}

	/**
	 * @param context
	 * @return value of ProxyHost
	 */
	public final java.lang.String getProxyHost(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.ProxyHost.toString());
	}

	/**
	 * Set value of ProxyHost
	 * @param proxyhost
	 */
	public final void setProxyHost(java.lang.String proxyhost)
	{
		setProxyHost(getContext(), proxyhost);
	}

	/**
	 * Set value of ProxyHost
	 * @param context
	 * @param proxyhost
	 */
	public final void setProxyHost(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String proxyhost)
	{
		getMendixObject().setValue(context, MemberNames.ProxyHost.toString(), proxyhost);
	}

	/**
	 * @return value of ProxyPort
	 */
	public final java.lang.Integer getProxyPort()
	{
		return getProxyPort(getContext());
	}

	/**
	 * @param context
	 * @return value of ProxyPort
	 */
	public final java.lang.Integer getProxyPort(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.Integer) getMendixObject().getValue(context, MemberNames.ProxyPort.toString());
	}

	/**
	 * Set value of ProxyPort
	 * @param proxyport
	 */
	public final void setProxyPort(java.lang.Integer proxyport)
	{
		setProxyPort(getContext(), proxyport);
	}

	/**
	 * Set value of ProxyPort
	 * @param context
	 * @param proxyport
	 */
	public final void setProxyPort(com.mendix.systemwideinterfaces.core.IContext context, java.lang.Integer proxyport)
	{
		getMendixObject().setValue(context, MemberNames.ProxyPort.toString(), proxyport);
	}

	/**
	 * @return value of ProxyUsername
	 */
	public final java.lang.String getProxyUsername()
	{
		return getProxyUsername(getContext());
	}

	/**
	 * @param context
	 * @return value of ProxyUsername
	 */
	public final java.lang.String getProxyUsername(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.ProxyUsername.toString());
	}

	/**
	 * Set value of ProxyUsername
	 * @param proxyusername
	 */
	public final void setProxyUsername(java.lang.String proxyusername)
	{
		setProxyUsername(getContext(), proxyusername);
	}

	/**
	 * Set value of ProxyUsername
	 * @param context
	 * @param proxyusername
	 */
	public final void setProxyUsername(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String proxyusername)
	{
		getMendixObject().setValue(context, MemberNames.ProxyUsername.toString(), proxyusername);
	}

	/**
	 * @return value of ProxyPassword
	 */
	public final java.lang.String getProxyPassword()
	{
		return getProxyPassword(getContext());
	}

	/**
	 * @param context
	 * @return value of ProxyPassword
	 */
	public final java.lang.String getProxyPassword(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.ProxyPassword.toString());
	}

	/**
	 * Set value of ProxyPassword
	 * @param proxypassword
	 */
	public final void setProxyPassword(java.lang.String proxypassword)
	{
		setProxyPassword(getContext(), proxypassword);
	}

	/**
	 * Set value of ProxyPassword
	 * @param context
	 * @param proxypassword
	 */
	public final void setProxyPassword(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String proxypassword)
	{
		getMendixObject().setValue(context, MemberNames.ProxyPassword.toString(), proxypassword);
	}

	@java.lang.Override
	public final com.mendix.systemwideinterfaces.core.IMendixObject getMendixObject()
	{
		return consumedODataConfigurationMendixObject;
	}

	@java.lang.Override
	public final com.mendix.systemwideinterfaces.core.IContext getContext()
	{
		return context;
	}

	@java.lang.Override
	public boolean equals(Object obj)
	{
		if (obj == this) {
			return true;
		}
		if (obj != null && getClass().equals(obj.getClass()))
		{
			final system.proxies.ConsumedODataConfiguration that = (system.proxies.ConsumedODataConfiguration) obj;
			return getMendixObject().equals(that.getMendixObject());
		}
		return false;
	}

	@java.lang.Override
	public int hashCode()
	{
		return getMendixObject().hashCode();
	}

  /**
   * Gives full name ("Module.Entity" name) of the type of the entity.
   *
   * @return the name
   */
	public static java.lang.String getType()
	{
		return entityName;
	}
}
