// This file was generated by Mendix Studio Pro.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package system.proxies;

/**
 * The type of context to use for executing tasks in task queues.
 * * System: Execute in the system context.
 * * User: Execute in a user context for a specific user.
 * * Anonymous: Execute in a context for an anonymous user.
 */
public enum ContextType
{
	System("1fad9521-9811-4570-b157-c5c27b2d96a7"),
	User("14c36ea9-d4b4-4883-ad23-19b00f2a1a02"),
	Anonymous("8e104de4-b77b-4ed4-9e46-69420c85e6a1"),
	ScheduledEvent("986416af-8e93-4321-b95a-a09ea0504bb4");

	private final java.lang.String i18nCaptionKey;
	
	private ContextType(java.lang.String i18nCaptionKey)
	{
		this.i18nCaptionKey = i18nCaptionKey;
	}

	public java.lang.String getCaption(java.lang.String languageCode)
	{
		String caption = com.mendix.core.Core.getInternationalizedString(languageCode, i18nCaptionKey);
		return caption.isEmpty() ? getCaption() : caption;
	}

	public java.lang.String getCaption()
	{
		return com.mendix.core.Core.getInternationalizedString("en_US", i18nCaptionKey);
	}
}
