// This file was generated by Mendix Studio Pro.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package system.proxies;

public enum DeviceType
{
	Phone("14995df6-c780-4977-aee9-1bf31a9f3089"),
	Tablet("1209c7ed-28e2-4a1b-9d8e-3a62487db39f"),
	Desktop("c6fcd3aa-7ea8-4aca-88bc-de6542bd4afe");

	private final java.lang.String i18nCaptionKey;
	
	private DeviceType(java.lang.String i18nCaptionKey)
	{
		this.i18nCaptionKey = i18nCaptionKey;
	}

	public java.lang.String getCaption(java.lang.String languageCode)
	{
		String caption = com.mendix.core.Core.getInternationalizedString(languageCode, i18nCaptionKey);
		return caption.isEmpty() ? getCaption() : caption;
	}

	public java.lang.String getCaption()
	{
		return com.mendix.core.Core.getInternationalizedString("en_US", i18nCaptionKey);
	}
}
