// This file was generated by Mendix Studio Pro.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package system.proxies;

public enum EventStatus
{
	Running("e5a09578-41d0-4c81-a016-6293071f77b3"),
	Completed("63aca8cf-bc5a-4bdf-960d-616030d7671a"),
	Error("5d87b5df-e2c1-4949-8b7b-454f5706522f"),
	Stopped("c245b583-326c-4971-b94b-334c19eb555e");

	private final java.lang.String i18nCaptionKey;
	
	private EventStatus(java.lang.String i18nCaptionKey)
	{
		this.i18nCaptionKey = i18nCaptionKey;
	}

	public java.lang.String getCaption(java.lang.String languageCode)
	{
		String caption = com.mendix.core.Core.getInternationalizedString(languageCode, i18nCaptionKey);
		return caption.isEmpty() ? getCaption() : caption;
	}

	public java.lang.String getCaption()
	{
		return com.mendix.core.Core.getInternationalizedString("en_US", i18nCaptionKey);
	}
}
