// This file was generated by Mendix Studio Pro.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package system.proxies;

public enum ProxyConfiguration
{
	UseAppSettings("fb9117ef-0279-4980-b32b-7aeff5814461"),
	Override("a2f1f59f-d8f0-4112-90b5-f85955b5f7f0"),
	NoProxy("47947336-e329-423a-8a25-1a7d6769f336");

	private final java.lang.String i18nCaptionKey;
	
	private ProxyConfiguration(java.lang.String i18nCaptionKey)
	{
		this.i18nCaptionKey = i18nCaptionKey;
	}

	public java.lang.String getCaption(java.lang.String languageCode)
	{
		String caption = com.mendix.core.Core.getInternationalizedString(languageCode, i18nCaptionKey);
		return caption.isEmpty() ? getCaption() : caption;
	}

	public java.lang.String getCaption()
	{
		return com.mendix.core.Core.getInternationalizedString("en_US", i18nCaptionKey);
	}
}
