// This file was generated by Mendix Studio Pro.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package system.proxies;

/**
 * Represents that execution status of a task in a task queue.
 * * Idle: The task was created and is waiting to be executed.
 * * Running: The task is being executed.
 * * Completed: The task executed successfully. A System.ProcessedQueueTask is added to reflect this.
 * * Failed: The task is no longer executing, because an exception occurred. A System.ProcessedQueueTask containing the exception is added to reflect the failure. The task will not be retried.
 * * Retrying: Same as the 'Failed' status but the task will be retried.
 * * Aborted: The task is no longer executing, because the cluster node that was executing it went down. A System.ProcessedQueueTask is added to reflect this. The task will be retried on another cluster node.
 * * Incompatible: The task never executed, because the model changed in such a way that it cannot be executed anymore. This could be because the microflow was removed/renamed, the arguments were changed or the Task Queue was removed.
 */
public enum QueueTaskStatus
{
	Idle("714b3e7e-4166-4571-96d9-72389a7417d9"),
	Running("0864591f-f30c-42f1-9a53-e4429c628eb2"),
	Completed("3e473985-8836-497b-b81e-3d4db09fb499"),
	Failed("c96239e7-b150-4a70-a5ea-e80896548b6d"),
	Retrying("2f958d5d-4789-42ad-a9d9-07da5d996e1c"),
	Aborted("2f366a55-ea11-476d-b42a-1e995bdcd01b"),
	Incompatible("e0974409-54c5-4731-893d-3d726d891adc");

	private final java.lang.String i18nCaptionKey;
	
	private QueueTaskStatus(java.lang.String i18nCaptionKey)
	{
		this.i18nCaptionKey = i18nCaptionKey;
	}

	public java.lang.String getCaption(java.lang.String languageCode)
	{
		String caption = com.mendix.core.Core.getInternationalizedString(languageCode, i18nCaptionKey);
		return caption.isEmpty() ? getCaption() : caption;
	}

	public java.lang.String getCaption()
	{
		return com.mendix.core.Core.getInternationalizedString("en_US", i18nCaptionKey);
	}
}
