// This file was generated by Mendix Studio Pro.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package system.proxies;

public enum WorkflowCurrentActivityAction
{
	DoNothing("0be952b8-d392-40ea-a7e0-ea51c96fef06"),
	JumpTo("f6554dd4-1328-4f13-bfd7-a27278a10f5b");

	private final java.lang.String i18nCaptionKey;
	
	private WorkflowCurrentActivityAction(java.lang.String i18nCaptionKey)
	{
		this.i18nCaptionKey = i18nCaptionKey;
	}

	public java.lang.String getCaption(java.lang.String languageCode)
	{
		String caption = com.mendix.core.Core.getInternationalizedString(languageCode, i18nCaptionKey);
		return caption.isEmpty() ? getCaption() : caption;
	}

	public java.lang.String getCaption()
	{
		return com.mendix.core.Core.getInternationalizedString("en_US", i18nCaptionKey);
	}
}
