// This file was generated by Mendix Studio Pro.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package system.proxies;

/**
 * Outcomes for ended multiuser tasks
 */
public class WorkflowEndedUserTaskOutcome implements com.mendix.systemwideinterfaces.core.IEntityProxy
{
	private final com.mendix.systemwideinterfaces.core.IMendixObject workflowEndedUserTaskOutcomeMendixObject;

	private final com.mendix.systemwideinterfaces.core.IContext context;

	/**
	 * Internal name of this entity
	 */
	public static final java.lang.String entityName = "System.WorkflowEndedUserTaskOutcome";

	/**
	 * Enum describing members of this entity
	 */
	public enum MemberNames
	{
		Outcome("Outcome"),
		Time("Time"),
		WorkflowEndedUserTaskOutcome_User("System.WorkflowEndedUserTaskOutcome_User"),
		WorkflowEndedUserTaskOutcome_WorkflowEndedUserTask("System.WorkflowEndedUserTaskOutcome_WorkflowEndedUserTask");

		private final java.lang.String metaName;

		MemberNames(java.lang.String s)
		{
			metaName = s;
		}

		@java.lang.Override
		public java.lang.String toString()
		{
			return metaName;
		}
	}

	public WorkflowEndedUserTaskOutcome(com.mendix.systemwideinterfaces.core.IContext context)
	{
		this(context, com.mendix.core.Core.instantiate(context, entityName));
	}

	protected WorkflowEndedUserTaskOutcome(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject workflowEndedUserTaskOutcomeMendixObject)
	{
		if (workflowEndedUserTaskOutcomeMendixObject == null) {
			throw new java.lang.IllegalArgumentException("The given object cannot be null.");
		}
		if (!workflowEndedUserTaskOutcomeMendixObject.isInstanceOf(entityName)) {
			throw new java.lang.IllegalArgumentException(String.format("The given object is not a %s", entityName));
		}	

		this.workflowEndedUserTaskOutcomeMendixObject = workflowEndedUserTaskOutcomeMendixObject;
		this.context = context;
	}

	/**
	 * Initialize a proxy using context (recommended). This context will be used for security checking when the get- and set-methods without context parameters are called.
	 * The get- and set-methods with context parameter should be used when for instance sudo access is necessary (IContext.createSudoClone() can be used to obtain sudo access).
	 * @param context The context to be used
	 * @param mendixObject The Mendix object for the new instance
	 * @return a new instance of this proxy class
	 */
	public static system.proxies.WorkflowEndedUserTaskOutcome initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject mendixObject)
	{
		return new system.proxies.WorkflowEndedUserTaskOutcome(context, mendixObject);
	}

	public static system.proxies.WorkflowEndedUserTaskOutcome load(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		com.mendix.systemwideinterfaces.core.IMendixObject mendixObject = com.mendix.core.Core.retrieveId(context, mendixIdentifier);
		return system.proxies.WorkflowEndedUserTaskOutcome.initialize(context, mendixObject);
	}

	public static java.util.List<system.proxies.WorkflowEndedUserTaskOutcome> load(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String xpathConstraint) throws com.mendix.core.CoreException
	{
		return com.mendix.core.Core.createXPathQuery(String.format("//%1$s%2$s", entityName, xpathConstraint))
			.execute(context)
			.stream()
			.map(obj -> system.proxies.WorkflowEndedUserTaskOutcome.initialize(context, obj))
			.collect(java.util.stream.Collectors.toList());
	}

	/**
	 * @return value of Outcome
	 */
	public final java.lang.String getOutcome()
	{
		return getOutcome(getContext());
	}

	/**
	 * @param context
	 * @return value of Outcome
	 */
	public final java.lang.String getOutcome(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.Outcome.toString());
	}

	/**
	 * Set value of Outcome
	 * @param outcome
	 */
	public final void setOutcome(java.lang.String outcome)
	{
		setOutcome(getContext(), outcome);
	}

	/**
	 * Set value of Outcome
	 * @param context
	 * @param outcome
	 */
	public final void setOutcome(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String outcome)
	{
		getMendixObject().setValue(context, MemberNames.Outcome.toString(), outcome);
	}

	/**
	 * @return value of Time
	 */
	public final java.util.Date getTime()
	{
		return getTime(getContext());
	}

	/**
	 * @param context
	 * @return value of Time
	 */
	public final java.util.Date getTime(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.util.Date) getMendixObject().getValue(context, MemberNames.Time.toString());
	}

	/**
	 * Set value of Time
	 * @param time
	 */
	public final void setTime(java.util.Date time)
	{
		setTime(getContext(), time);
	}

	/**
	 * Set value of Time
	 * @param context
	 * @param time
	 */
	public final void setTime(com.mendix.systemwideinterfaces.core.IContext context, java.util.Date time)
	{
		getMendixObject().setValue(context, MemberNames.Time.toString(), time);
	}

	/**
	 * @throws com.mendix.core.CoreException
	 * @return value of WorkflowEndedUserTaskOutcome_User
	 */
	public final system.proxies.User getWorkflowEndedUserTaskOutcome_User() throws com.mendix.core.CoreException
	{
		return getWorkflowEndedUserTaskOutcome_User(getContext());
	}

	/**
	 * @param context
	 * @return value of WorkflowEndedUserTaskOutcome_User
	 * @throws com.mendix.core.CoreException
	 */
	public final system.proxies.User getWorkflowEndedUserTaskOutcome_User(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		system.proxies.User result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.WorkflowEndedUserTaskOutcome_User.toString());
		if (identifier != null) {
			result = system.proxies.User.load(context, identifier);
		}
		return result;
	}

	/**
	 * Set value of WorkflowEndedUserTaskOutcome_User
	 * @param workflowendedusertaskoutcome_user
	 */
	public final void setWorkflowEndedUserTaskOutcome_User(system.proxies.User workflowendedusertaskoutcome_user)
	{
		setWorkflowEndedUserTaskOutcome_User(getContext(), workflowendedusertaskoutcome_user);
	}

	/**
	 * Set value of WorkflowEndedUserTaskOutcome_User
	 * @param context
	 * @param workflowendedusertaskoutcome_user
	 */
	public final void setWorkflowEndedUserTaskOutcome_User(com.mendix.systemwideinterfaces.core.IContext context, system.proxies.User workflowendedusertaskoutcome_user)
	{
		if (workflowendedusertaskoutcome_user == null) {
			getMendixObject().setValue(context, MemberNames.WorkflowEndedUserTaskOutcome_User.toString(), null);
		} else {
			getMendixObject().setValue(context, MemberNames.WorkflowEndedUserTaskOutcome_User.toString(), workflowendedusertaskoutcome_user.getMendixObject().getId());
		}
	}

	/**
	 * @throws com.mendix.core.CoreException
	 * @return value of WorkflowEndedUserTaskOutcome_WorkflowEndedUserTask
	 */
	public final system.proxies.WorkflowEndedUserTask getWorkflowEndedUserTaskOutcome_WorkflowEndedUserTask() throws com.mendix.core.CoreException
	{
		return getWorkflowEndedUserTaskOutcome_WorkflowEndedUserTask(getContext());
	}

	/**
	 * @param context
	 * @return value of WorkflowEndedUserTaskOutcome_WorkflowEndedUserTask
	 * @throws com.mendix.core.CoreException
	 */
	public final system.proxies.WorkflowEndedUserTask getWorkflowEndedUserTaskOutcome_WorkflowEndedUserTask(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		system.proxies.WorkflowEndedUserTask result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.WorkflowEndedUserTaskOutcome_WorkflowEndedUserTask.toString());
		if (identifier != null) {
			result = system.proxies.WorkflowEndedUserTask.load(context, identifier);
		}
		return result;
	}

	/**
	 * Set value of WorkflowEndedUserTaskOutcome_WorkflowEndedUserTask
	 * @param workflowendedusertaskoutcome_workflowendedusertask
	 */
	public final void setWorkflowEndedUserTaskOutcome_WorkflowEndedUserTask(system.proxies.WorkflowEndedUserTask workflowendedusertaskoutcome_workflowendedusertask)
	{
		setWorkflowEndedUserTaskOutcome_WorkflowEndedUserTask(getContext(), workflowendedusertaskoutcome_workflowendedusertask);
	}

	/**
	 * Set value of WorkflowEndedUserTaskOutcome_WorkflowEndedUserTask
	 * @param context
	 * @param workflowendedusertaskoutcome_workflowendedusertask
	 */
	public final void setWorkflowEndedUserTaskOutcome_WorkflowEndedUserTask(com.mendix.systemwideinterfaces.core.IContext context, system.proxies.WorkflowEndedUserTask workflowendedusertaskoutcome_workflowendedusertask)
	{
		if (workflowendedusertaskoutcome_workflowendedusertask == null) {
			getMendixObject().setValue(context, MemberNames.WorkflowEndedUserTaskOutcome_WorkflowEndedUserTask.toString(), null);
		} else {
			getMendixObject().setValue(context, MemberNames.WorkflowEndedUserTaskOutcome_WorkflowEndedUserTask.toString(), workflowendedusertaskoutcome_workflowendedusertask.getMendixObject().getId());
		}
	}

	@java.lang.Override
	public final com.mendix.systemwideinterfaces.core.IMendixObject getMendixObject()
	{
		return workflowEndedUserTaskOutcomeMendixObject;
	}

	@java.lang.Override
	public final com.mendix.systemwideinterfaces.core.IContext getContext()
	{
		return context;
	}

	@java.lang.Override
	public boolean equals(Object obj)
	{
		if (obj == this) {
			return true;
		}
		if (obj != null && getClass().equals(obj.getClass()))
		{
			final system.proxies.WorkflowEndedUserTaskOutcome that = (system.proxies.WorkflowEndedUserTaskOutcome) obj;
			return getMendixObject().equals(that.getMendixObject());
		}
		return false;
	}

	@java.lang.Override
	public int hashCode()
	{
		return getMendixObject().hashCode();
	}

  /**
   * Gives full name ("Module.Entity" name) of the type of the entity.
   *
   * @return the name
   */
	public static java.lang.String getType()
	{
		return entityName;
	}
}
