// This file was generated by Mendix Studio Pro.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package system.proxies;

/**
 * Represents ended workflow user tasks. This includes Completed and Aborted user tasks. 
 */
public class WorkflowEndedUserTask implements com.mendix.systemwideinterfaces.core.IEntityProxy
{
	private final com.mendix.systemwideinterfaces.core.IMendixObject workflowEndedUserTaskMendixObject;

	private final com.mendix.systemwideinterfaces.core.IContext context;

	/**
	 * Internal name of this entity
	 */
	public static final java.lang.String entityName = "System.WorkflowEndedUserTask";

	/**
	 * Enum describing members of this entity
	 */
	public enum MemberNames
	{
		Name("Name"),
		Description("Description"),
		StartTime("StartTime"),
		DueDate("DueDate"),
		EndTime("EndTime"),
		Outcome("Outcome"),
		State("State"),
		CompletionType("CompletionType"),
		UserTaskKey("UserTaskKey"),
		WorkflowEndedUserTask_Assignees("System.WorkflowEndedUserTask_Assignees"),
		WorkflowEndedUserTask_TargetUsers("System.WorkflowEndedUserTask_TargetUsers"),
		WorkflowEndedUserTask_WorkflowUserTaskDefinition("System.WorkflowEndedUserTask_WorkflowUserTaskDefinition"),
		WorkflowEndedUserTask_Workflow("System.WorkflowEndedUserTask_Workflow"),
		WorkflowEndedUserTask_TargetGroups("System.WorkflowEndedUserTask_TargetGroups");

		private final java.lang.String metaName;

		MemberNames(java.lang.String s)
		{
			metaName = s;
		}

		@java.lang.Override
		public java.lang.String toString()
		{
			return metaName;
		}
	}

	public WorkflowEndedUserTask(com.mendix.systemwideinterfaces.core.IContext context)
	{
		this(context, com.mendix.core.Core.instantiate(context, entityName));
	}

	protected WorkflowEndedUserTask(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject workflowEndedUserTaskMendixObject)
	{
		if (workflowEndedUserTaskMendixObject == null) {
			throw new java.lang.IllegalArgumentException("The given object cannot be null.");
		}
		if (!workflowEndedUserTaskMendixObject.isInstanceOf(entityName)) {
			throw new java.lang.IllegalArgumentException(String.format("The given object is not a %s", entityName));
		}	

		this.workflowEndedUserTaskMendixObject = workflowEndedUserTaskMendixObject;
		this.context = context;
	}

	/**
	 * Initialize a proxy using context (recommended). This context will be used for security checking when the get- and set-methods without context parameters are called.
	 * The get- and set-methods with context parameter should be used when for instance sudo access is necessary (IContext.createSudoClone() can be used to obtain sudo access).
	 * @param context The context to be used
	 * @param mendixObject The Mendix object for the new instance
	 * @return a new instance of this proxy class
	 */
	public static system.proxies.WorkflowEndedUserTask initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject mendixObject)
	{
		return new system.proxies.WorkflowEndedUserTask(context, mendixObject);
	}

	public static system.proxies.WorkflowEndedUserTask load(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		com.mendix.systemwideinterfaces.core.IMendixObject mendixObject = com.mendix.core.Core.retrieveId(context, mendixIdentifier);
		return system.proxies.WorkflowEndedUserTask.initialize(context, mendixObject);
	}

	public static java.util.List<system.proxies.WorkflowEndedUserTask> load(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String xpathConstraint) throws com.mendix.core.CoreException
	{
		return com.mendix.core.Core.createXPathQuery(String.format("//%1$s%2$s", entityName, xpathConstraint))
			.execute(context)
			.stream()
			.map(obj -> system.proxies.WorkflowEndedUserTask.initialize(context, obj))
			.collect(java.util.stream.Collectors.toList());
	}

	/**
	 * @return value of Name
	 */
	public final java.lang.String getName()
	{
		return getName(getContext());
	}

	/**
	 * @param context
	 * @return value of Name
	 */
	public final java.lang.String getName(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.Name.toString());
	}

	/**
	 * Set value of Name
	 * @param name
	 */
	public final void setName(java.lang.String name)
	{
		setName(getContext(), name);
	}

	/**
	 * Set value of Name
	 * @param context
	 * @param name
	 */
	public final void setName(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String name)
	{
		getMendixObject().setValue(context, MemberNames.Name.toString(), name);
	}

	/**
	 * @return value of Description
	 */
	public final java.lang.String getDescription()
	{
		return getDescription(getContext());
	}

	/**
	 * @param context
	 * @return value of Description
	 */
	public final java.lang.String getDescription(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.Description.toString());
	}

	/**
	 * Set value of Description
	 * @param description
	 */
	public final void setDescription(java.lang.String description)
	{
		setDescription(getContext(), description);
	}

	/**
	 * Set value of Description
	 * @param context
	 * @param description
	 */
	public final void setDescription(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String description)
	{
		getMendixObject().setValue(context, MemberNames.Description.toString(), description);
	}

	/**
	 * @return value of StartTime
	 */
	public final java.util.Date getStartTime()
	{
		return getStartTime(getContext());
	}

	/**
	 * @param context
	 * @return value of StartTime
	 */
	public final java.util.Date getStartTime(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.util.Date) getMendixObject().getValue(context, MemberNames.StartTime.toString());
	}

	/**
	 * Set value of StartTime
	 * @param starttime
	 */
	public final void setStartTime(java.util.Date starttime)
	{
		setStartTime(getContext(), starttime);
	}

	/**
	 * Set value of StartTime
	 * @param context
	 * @param starttime
	 */
	public final void setStartTime(com.mendix.systemwideinterfaces.core.IContext context, java.util.Date starttime)
	{
		getMendixObject().setValue(context, MemberNames.StartTime.toString(), starttime);
	}

	/**
	 * @return value of DueDate
	 */
	public final java.util.Date getDueDate()
	{
		return getDueDate(getContext());
	}

	/**
	 * @param context
	 * @return value of DueDate
	 */
	public final java.util.Date getDueDate(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.util.Date) getMendixObject().getValue(context, MemberNames.DueDate.toString());
	}

	/**
	 * Set value of DueDate
	 * @param duedate
	 */
	public final void setDueDate(java.util.Date duedate)
	{
		setDueDate(getContext(), duedate);
	}

	/**
	 * Set value of DueDate
	 * @param context
	 * @param duedate
	 */
	public final void setDueDate(com.mendix.systemwideinterfaces.core.IContext context, java.util.Date duedate)
	{
		getMendixObject().setValue(context, MemberNames.DueDate.toString(), duedate);
	}

	/**
	 * @return value of EndTime
	 */
	public final java.util.Date getEndTime()
	{
		return getEndTime(getContext());
	}

	/**
	 * @param context
	 * @return value of EndTime
	 */
	public final java.util.Date getEndTime(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.util.Date) getMendixObject().getValue(context, MemberNames.EndTime.toString());
	}

	/**
	 * Set value of EndTime
	 * @param endtime
	 */
	public final void setEndTime(java.util.Date endtime)
	{
		setEndTime(getContext(), endtime);
	}

	/**
	 * Set value of EndTime
	 * @param context
	 * @param endtime
	 */
	public final void setEndTime(com.mendix.systemwideinterfaces.core.IContext context, java.util.Date endtime)
	{
		getMendixObject().setValue(context, MemberNames.EndTime.toString(), endtime);
	}

	/**
	 * @return value of Outcome
	 */
	public final java.lang.String getOutcome()
	{
		return getOutcome(getContext());
	}

	/**
	 * @param context
	 * @return value of Outcome
	 */
	public final java.lang.String getOutcome(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.Outcome.toString());
	}

	/**
	 * Set value of Outcome
	 * @param outcome
	 */
	public final void setOutcome(java.lang.String outcome)
	{
		setOutcome(getContext(), outcome);
	}

	/**
	 * Set value of Outcome
	 * @param context
	 * @param outcome
	 */
	public final void setOutcome(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String outcome)
	{
		getMendixObject().setValue(context, MemberNames.Outcome.toString(), outcome);
	}

	/**
	 * Get value of State
	 * @param state
	 */
	public final system.proxies.WorkflowUserTaskState getState()
	{
		return getState(getContext());
	}

	/**
	 * @param context
	 * @return value of State
	 */
	public final system.proxies.WorkflowUserTaskState getState(com.mendix.systemwideinterfaces.core.IContext context)
	{
		Object obj = getMendixObject().getValue(context, MemberNames.State.toString());
		if (obj == null) {
			return null;
		}
		return system.proxies.WorkflowUserTaskState.valueOf((java.lang.String) obj);
	}

	/**
	 * Set value of State
	 * @param state
	 */
	public final void setState(system.proxies.WorkflowUserTaskState state)
	{
		setState(getContext(), state);
	}

	/**
	 * Set value of State
	 * @param context
	 * @param state
	 */
	public final void setState(com.mendix.systemwideinterfaces.core.IContext context, system.proxies.WorkflowUserTaskState state)
	{
		if (state != null) {
			getMendixObject().setValue(context, MemberNames.State.toString(), state.toString());
		} else {
			getMendixObject().setValue(context, MemberNames.State.toString(), null);
		}
	}

	/**
	 * Get value of CompletionType
	 * @param completiontype
	 */
	public final system.proxies.WorkflowUserTaskCompletionType getCompletionType()
	{
		return getCompletionType(getContext());
	}

	/**
	 * @param context
	 * @return value of CompletionType
	 */
	public final system.proxies.WorkflowUserTaskCompletionType getCompletionType(com.mendix.systemwideinterfaces.core.IContext context)
	{
		Object obj = getMendixObject().getValue(context, MemberNames.CompletionType.toString());
		if (obj == null) {
			return null;
		}
		return system.proxies.WorkflowUserTaskCompletionType.valueOf((java.lang.String) obj);
	}

	/**
	 * Set value of CompletionType
	 * @param completiontype
	 */
	public final void setCompletionType(system.proxies.WorkflowUserTaskCompletionType completiontype)
	{
		setCompletionType(getContext(), completiontype);
	}

	/**
	 * Set value of CompletionType
	 * @param context
	 * @param completiontype
	 */
	public final void setCompletionType(com.mendix.systemwideinterfaces.core.IContext context, system.proxies.WorkflowUserTaskCompletionType completiontype)
	{
		if (completiontype != null) {
			getMendixObject().setValue(context, MemberNames.CompletionType.toString(), completiontype.toString());
		} else {
			getMendixObject().setValue(context, MemberNames.CompletionType.toString(), null);
		}
	}

	/**
	 * @return value of UserTaskKey
	 */
	public final java.lang.String getUserTaskKey()
	{
		return getUserTaskKey(getContext());
	}

	/**
	 * @param context
	 * @return value of UserTaskKey
	 */
	public final java.lang.String getUserTaskKey(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.UserTaskKey.toString());
	}

	/**
	 * Set value of UserTaskKey
	 * @param usertaskkey
	 */
	public final void setUserTaskKey(java.lang.String usertaskkey)
	{
		setUserTaskKey(getContext(), usertaskkey);
	}

	/**
	 * Set value of UserTaskKey
	 * @param context
	 * @param usertaskkey
	 */
	public final void setUserTaskKey(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String usertaskkey)
	{
		getMendixObject().setValue(context, MemberNames.UserTaskKey.toString(), usertaskkey);
	}

	/**
	 * @throws com.mendix.core.CoreException
	 * @return value of WorkflowEndedUserTask_Assignees
	 */
	public final java.util.List<system.proxies.User> getWorkflowEndedUserTask_Assignees() throws com.mendix.core.CoreException
	{
		return getWorkflowEndedUserTask_Assignees(getContext());
	}

	/**
	 * @param context
	 * @return value of WorkflowEndedUserTask_Assignees
	 * @throws com.mendix.core.CoreException
	 */
	@SuppressWarnings("unchecked")
	public final java.util.List<system.proxies.User> getWorkflowEndedUserTask_Assignees(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		java.util.List<system.proxies.User> result = new java.util.ArrayList<>();
		Object valueObject = getMendixObject().getValue(context, MemberNames.WorkflowEndedUserTask_Assignees.toString());
		if (valueObject == null) {
			return result;
		}
		for (com.mendix.systemwideinterfaces.core.IMendixObject mendixObject : com.mendix.core.Core.retrieveIdList(context, (java.util.List<com.mendix.systemwideinterfaces.core.IMendixIdentifier>) valueObject)) {
			result.add(system.proxies.User.initialize(context, mendixObject));
		}
		return result;
	}

	/**
	 * Set value of WorkflowEndedUserTask_Assignees
	 * @param workflowendedusertask_assignees
	 */
	public final void setWorkflowEndedUserTask_Assignees(java.util.List<system.proxies.User> workflowendedusertask_assignees)
	{
		setWorkflowEndedUserTask_Assignees(getContext(), workflowendedusertask_assignees);
	}

	/**
	 * Set value of WorkflowEndedUserTask_Assignees
	 * @param context
	 * @param workflowendedusertask_assignees
	 */
	public final void setWorkflowEndedUserTask_Assignees(com.mendix.systemwideinterfaces.core.IContext context, java.util.List<system.proxies.User> workflowendedusertask_assignees)
	{
		var identifiers = workflowendedusertask_assignees
			.stream()
			.map(proxyObject -> proxyObject.getMendixObject().getId())
			.collect(java.util.stream.Collectors.toList());
		
		getMendixObject().setValue(context, MemberNames.WorkflowEndedUserTask_Assignees.toString(), identifiers);
	}

	/**
	 * @throws com.mendix.core.CoreException
	 * @return value of WorkflowEndedUserTask_TargetUsers
	 */
	public final java.util.List<system.proxies.User> getWorkflowEndedUserTask_TargetUsers() throws com.mendix.core.CoreException
	{
		return getWorkflowEndedUserTask_TargetUsers(getContext());
	}

	/**
	 * @param context
	 * @return value of WorkflowEndedUserTask_TargetUsers
	 * @throws com.mendix.core.CoreException
	 */
	@SuppressWarnings("unchecked")
	public final java.util.List<system.proxies.User> getWorkflowEndedUserTask_TargetUsers(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		java.util.List<system.proxies.User> result = new java.util.ArrayList<>();
		Object valueObject = getMendixObject().getValue(context, MemberNames.WorkflowEndedUserTask_TargetUsers.toString());
		if (valueObject == null) {
			return result;
		}
		for (com.mendix.systemwideinterfaces.core.IMendixObject mendixObject : com.mendix.core.Core.retrieveIdList(context, (java.util.List<com.mendix.systemwideinterfaces.core.IMendixIdentifier>) valueObject)) {
			result.add(system.proxies.User.initialize(context, mendixObject));
		}
		return result;
	}

	/**
	 * Set value of WorkflowEndedUserTask_TargetUsers
	 * @param workflowendedusertask_targetusers
	 */
	public final void setWorkflowEndedUserTask_TargetUsers(java.util.List<system.proxies.User> workflowendedusertask_targetusers)
	{
		setWorkflowEndedUserTask_TargetUsers(getContext(), workflowendedusertask_targetusers);
	}

	/**
	 * Set value of WorkflowEndedUserTask_TargetUsers
	 * @param context
	 * @param workflowendedusertask_targetusers
	 */
	public final void setWorkflowEndedUserTask_TargetUsers(com.mendix.systemwideinterfaces.core.IContext context, java.util.List<system.proxies.User> workflowendedusertask_targetusers)
	{
		var identifiers = workflowendedusertask_targetusers
			.stream()
			.map(proxyObject -> proxyObject.getMendixObject().getId())
			.collect(java.util.stream.Collectors.toList());
		
		getMendixObject().setValue(context, MemberNames.WorkflowEndedUserTask_TargetUsers.toString(), identifiers);
	}

	/**
	 * @throws com.mendix.core.CoreException
	 * @return value of WorkflowEndedUserTask_WorkflowUserTaskDefinition
	 */
	public final system.proxies.WorkflowUserTaskDefinition getWorkflowEndedUserTask_WorkflowUserTaskDefinition() throws com.mendix.core.CoreException
	{
		return getWorkflowEndedUserTask_WorkflowUserTaskDefinition(getContext());
	}

	/**
	 * @param context
	 * @return value of WorkflowEndedUserTask_WorkflowUserTaskDefinition
	 * @throws com.mendix.core.CoreException
	 */
	public final system.proxies.WorkflowUserTaskDefinition getWorkflowEndedUserTask_WorkflowUserTaskDefinition(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		system.proxies.WorkflowUserTaskDefinition result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.WorkflowEndedUserTask_WorkflowUserTaskDefinition.toString());
		if (identifier != null) {
			result = system.proxies.WorkflowUserTaskDefinition.load(context, identifier);
		}
		return result;
	}

	/**
	 * Set value of WorkflowEndedUserTask_WorkflowUserTaskDefinition
	 * @param workflowendedusertask_workflowusertaskdefinition
	 */
	public final void setWorkflowEndedUserTask_WorkflowUserTaskDefinition(system.proxies.WorkflowUserTaskDefinition workflowendedusertask_workflowusertaskdefinition)
	{
		setWorkflowEndedUserTask_WorkflowUserTaskDefinition(getContext(), workflowendedusertask_workflowusertaskdefinition);
	}

	/**
	 * Set value of WorkflowEndedUserTask_WorkflowUserTaskDefinition
	 * @param context
	 * @param workflowendedusertask_workflowusertaskdefinition
	 */
	public final void setWorkflowEndedUserTask_WorkflowUserTaskDefinition(com.mendix.systemwideinterfaces.core.IContext context, system.proxies.WorkflowUserTaskDefinition workflowendedusertask_workflowusertaskdefinition)
	{
		if (workflowendedusertask_workflowusertaskdefinition == null) {
			getMendixObject().setValue(context, MemberNames.WorkflowEndedUserTask_WorkflowUserTaskDefinition.toString(), null);
		} else {
			getMendixObject().setValue(context, MemberNames.WorkflowEndedUserTask_WorkflowUserTaskDefinition.toString(), workflowendedusertask_workflowusertaskdefinition.getMendixObject().getId());
		}
	}

	/**
	 * @throws com.mendix.core.CoreException
	 * @return value of WorkflowEndedUserTask_Workflow
	 */
	public final system.proxies.Workflow getWorkflowEndedUserTask_Workflow() throws com.mendix.core.CoreException
	{
		return getWorkflowEndedUserTask_Workflow(getContext());
	}

	/**
	 * @param context
	 * @return value of WorkflowEndedUserTask_Workflow
	 * @throws com.mendix.core.CoreException
	 */
	public final system.proxies.Workflow getWorkflowEndedUserTask_Workflow(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		system.proxies.Workflow result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.WorkflowEndedUserTask_Workflow.toString());
		if (identifier != null) {
			result = system.proxies.Workflow.load(context, identifier);
		}
		return result;
	}

	/**
	 * Set value of WorkflowEndedUserTask_Workflow
	 * @param workflowendedusertask_workflow
	 */
	public final void setWorkflowEndedUserTask_Workflow(system.proxies.Workflow workflowendedusertask_workflow)
	{
		setWorkflowEndedUserTask_Workflow(getContext(), workflowendedusertask_workflow);
	}

	/**
	 * Set value of WorkflowEndedUserTask_Workflow
	 * @param context
	 * @param workflowendedusertask_workflow
	 */
	public final void setWorkflowEndedUserTask_Workflow(com.mendix.systemwideinterfaces.core.IContext context, system.proxies.Workflow workflowendedusertask_workflow)
	{
		if (workflowendedusertask_workflow == null) {
			getMendixObject().setValue(context, MemberNames.WorkflowEndedUserTask_Workflow.toString(), null);
		} else {
			getMendixObject().setValue(context, MemberNames.WorkflowEndedUserTask_Workflow.toString(), workflowendedusertask_workflow.getMendixObject().getId());
		}
	}

	/**
	 * @throws com.mendix.core.CoreException
	 * @return value of WorkflowEndedUserTask_TargetGroups
	 */
	public final java.util.List<system.proxies.WorkflowGroup> getWorkflowEndedUserTask_TargetGroups() throws com.mendix.core.CoreException
	{
		return getWorkflowEndedUserTask_TargetGroups(getContext());
	}

	/**
	 * @param context
	 * @return value of WorkflowEndedUserTask_TargetGroups
	 * @throws com.mendix.core.CoreException
	 */
	@SuppressWarnings("unchecked")
	public final java.util.List<system.proxies.WorkflowGroup> getWorkflowEndedUserTask_TargetGroups(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		java.util.List<system.proxies.WorkflowGroup> result = new java.util.ArrayList<>();
		Object valueObject = getMendixObject().getValue(context, MemberNames.WorkflowEndedUserTask_TargetGroups.toString());
		if (valueObject == null) {
			return result;
		}
		for (com.mendix.systemwideinterfaces.core.IMendixObject mendixObject : com.mendix.core.Core.retrieveIdList(context, (java.util.List<com.mendix.systemwideinterfaces.core.IMendixIdentifier>) valueObject)) {
			result.add(system.proxies.WorkflowGroup.initialize(context, mendixObject));
		}
		return result;
	}

	/**
	 * Set value of WorkflowEndedUserTask_TargetGroups
	 * @param workflowendedusertask_targetgroups
	 */
	public final void setWorkflowEndedUserTask_TargetGroups(java.util.List<system.proxies.WorkflowGroup> workflowendedusertask_targetgroups)
	{
		setWorkflowEndedUserTask_TargetGroups(getContext(), workflowendedusertask_targetgroups);
	}

	/**
	 * Set value of WorkflowEndedUserTask_TargetGroups
	 * @param context
	 * @param workflowendedusertask_targetgroups
	 */
	public final void setWorkflowEndedUserTask_TargetGroups(com.mendix.systemwideinterfaces.core.IContext context, java.util.List<system.proxies.WorkflowGroup> workflowendedusertask_targetgroups)
	{
		var identifiers = workflowendedusertask_targetgroups
			.stream()
			.map(proxyObject -> proxyObject.getMendixObject().getId())
			.collect(java.util.stream.Collectors.toList());
		
		getMendixObject().setValue(context, MemberNames.WorkflowEndedUserTask_TargetGroups.toString(), identifiers);
	}

	@java.lang.Override
	public final com.mendix.systemwideinterfaces.core.IMendixObject getMendixObject()
	{
		return workflowEndedUserTaskMendixObject;
	}

	@java.lang.Override
	public final com.mendix.systemwideinterfaces.core.IContext getContext()
	{
		return context;
	}

	@java.lang.Override
	public boolean equals(Object obj)
	{
		if (obj == this) {
			return true;
		}
		if (obj != null && getClass().equals(obj.getClass()))
		{
			final system.proxies.WorkflowEndedUserTask that = (system.proxies.WorkflowEndedUserTask) obj;
			return getMendixObject().equals(that.getMendixObject());
		}
		return false;
	}

	@java.lang.Override
	public int hashCode()
	{
		return getMendixObject().hashCode();
	}

  /**
   * Gives full name ("Module.Entity" name) of the type of the entity.
   *
   * @return the name
   */
	public static java.lang.String getType()
	{
		return entityName;
	}
}
