// This file was generated by Mendix Studio Pro.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package datawidgets.proxies;

public enum Filter_Operators
{
	contains("6626acc4-a73a-44a8-86b1-bae5b451d342"),
	startsWith("4ba62078-f5e1-44e1-ba01-966c530184bc"),
	endsWith("5095665c-b4b6-483e-93e2-ffce329f9319"),
	between("5e4caebc-9334-482d-87e8-fe23f04b8f4e"),
	greater("537fb1e5-237c-418b-b675-178d83bea148"),
	greaterEqual("9c220a87-5e4f-43df-9058-fb5d05f1d1fd"),
	equal("c1001630-9c60-4b6b-a82b-7ec0286c20f6"),
	notEqual("7746a034-c987-44b1-ae2b-f4890b345009"),
	smaller("72966265-558a-4680-a28d-56218122125d"),
	smallerEqual("9ae965ea-5dfb-4291-88a5-a5f7bd70779b"),
	empty("829d71d1-6805-4074-89f4-cf6f7a7c2430"),
	notEmpty("f26e3c8f-dfb2-408c-98de-7d1bd7023384");

	private final java.lang.String i18nCaptionKey;
	
	private Filter_Operators(java.lang.String i18nCaptionKey)
	{
		this.i18nCaptionKey = i18nCaptionKey;
	}

	public java.lang.String getCaption(java.lang.String languageCode)
	{
		String caption = com.mendix.core.Core.getInternationalizedString(languageCode, i18nCaptionKey);
		return caption.isEmpty() ? getCaption() : caption;
	}

	public java.lang.String getCaption()
	{
		return com.mendix.core.Core.getInternationalizedString("en_US", i18nCaptionKey);
	}
}
