// This file was generated by Mendix Studio Pro.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package datawidgets.proxies;

public enum Filter_Operators
{
	contains("f2787673-3a6c-4685-852a-1b448b38f36c"),
	startsWith("015cecd8-dadb-481e-9bb3-f998482f54a8"),
	endsWith("cc99d356-a7e1-4adc-8b96-ac18de7fe08a"),
	between("286cd99d-471f-4ba4-a40f-a3915d8e483a"),
	greater("217f33f7-5051-4ea5-aff6-fcbfd5f04ca4"),
	greaterEqual("95bf34e8-4f50-4453-9454-5d05a6d779c8"),
	equal("d895d0f7-7641-4ae6-997b-54f65891910d"),
	notEqual("902e02cb-6f16-4339-92e8-5f8b433cbc29"),
	smaller("d7e1ebf7-4ae1-484e-b114-293caa2e2e84"),
	smallerEqual("7e083519-f89d-4672-81f1-d149113efbb3"),
	empty("1c80369b-a474-4787-b62d-6d15fb1dec37"),
	notEmpty("cc02ad0b-3253-4b91-b251-83f4a0ccfcfe");

	private final java.lang.String i18nCaptionKey;
	
	private Filter_Operators(java.lang.String i18nCaptionKey)
	{
		this.i18nCaptionKey = i18nCaptionKey;
	}

	public java.lang.String getCaption(java.lang.String languageCode)
	{
		String caption = com.mendix.core.Core.getInternationalizedString(languageCode, i18nCaptionKey);
		return caption.isEmpty() ? getCaption() : caption;
	}

	public java.lang.String getCaption()
	{
		return com.mendix.core.Core.getInternationalizedString("en_US", i18nCaptionKey);
	}
}
