// This file was generated by Mendix Studio Pro.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package nativemobileresources.proxies;

public enum Enum_PermissionStatus
{
	unavailable("e4309c52-4f49-4e73-80ab-7e2403daa885"),
	denied("9fc846c7-4e01-4461-b677-13a5abecdd16"),
	limited("96cf41de-6197-41ff-a934-2aaee9b1d27a"),
	granted("7adeef20-7714-4367-b3b4-482ab783c628"),
	blocked("5aa0a77b-c2c0-424a-8d0c-7b5244f47617");

	private final java.lang.String i18nCaptionKey;
	
	private Enum_PermissionStatus(java.lang.String i18nCaptionKey)
	{
		this.i18nCaptionKey = i18nCaptionKey;
	}

	public java.lang.String getCaption(java.lang.String languageCode)
	{
		String caption = com.mendix.core.Core.getInternationalizedString(languageCode, i18nCaptionKey);
		return caption.isEmpty() ? getCaption() : caption;
	}

	public java.lang.String getCaption()
	{
		return com.mendix.core.Core.getInternationalizedString("en_US", i18nCaptionKey);
	}
}
