// This file was generated by Mendix Studio Pro.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package nativemobileresources.proxies;

public enum Enum_PermissionStatus
{
	unavailable(new java.lang.String[][] { new java.lang.String[] { "en_US", "Unavailable" } }),
	denied(new java.lang.String[][] { new java.lang.String[] { "en_US", "Denied" } }),
	limited(new java.lang.String[][] { new java.lang.String[] { "en_US", "Limited" } }),
	granted(new java.lang.String[][] { new java.lang.String[] { "en_US", "Granted" } }),
	blocked(new java.lang.String[][] { new java.lang.String[] { "en_US", "Blocked" } });

	private final java.util.Map<java.lang.String, java.lang.String> captions;

	private Enum_PermissionStatus(java.lang.String[][] captionStrings)
	{
		this.captions = new java.util.HashMap<>();
		for (java.lang.String[] captionString : captionStrings) {
			captions.put(captionString[0], captionString[1]);
		}
	}

	public java.lang.String getCaption(java.lang.String languageCode)
	{
		return captions.getOrDefault(languageCode, "en_US");
	}

	public java.lang.String getCaption()
	{
		return captions.get("en_US");
	}
}
