// This file was generated by Mendix Studio Pro.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package nativemobileresources.proxies;

public enum Enum_PermissionStatus
{
	unavailable("32606e7a-9d83-4abe-824f-26916761a581"),
	denied("28af8a7c-ff21-4830-8288-ccc35fc699c0"),
	limited("3814be66-c505-4820-a110-6cc5a7db4ef7"),
	granted("f9646bc9-488c-4ee9-b6ed-76cdbaf5b209"),
	blocked("810084ba-9459-450f-90fb-aa3d07087fa1");

	private final java.lang.String i18nCaptionKey;
	
	private Enum_PermissionStatus(java.lang.String i18nCaptionKey)
	{
		this.i18nCaptionKey = i18nCaptionKey;
	}

	public java.lang.String getCaption(java.lang.String languageCode)
	{
		String caption = com.mendix.core.Core.getInternationalizedString(languageCode, i18nCaptionKey);
		return caption.isEmpty() ? getCaption() : caption;
	}

	public java.lang.String getCaption()
	{
		return com.mendix.core.Core.getInternationalizedString("en_US", i18nCaptionKey);
	}
}
