// This file was generated by Mendix Studio Pro.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package nativemobileresources.proxies;

public enum InAppBrowserDismissButtonStyle
{
	done("d9d89150-8895-48bc-b0c6-bc87a8c98b25"),
	close("1b9aef0a-d755-4852-911d-677b5563e5b2"),
	cancel("58f78ed0-5e65-4150-b4da-5b2546585230");

	private final java.lang.String i18nCaptionKey;
	
	private InAppBrowserDismissButtonStyle(java.lang.String i18nCaptionKey)
	{
		this.i18nCaptionKey = i18nCaptionKey;
	}

	public java.lang.String getCaption(java.lang.String languageCode)
	{
		String caption = com.mendix.core.Core.getInternationalizedString(languageCode, i18nCaptionKey);
		return caption.isEmpty() ? getCaption() : caption;
	}

	public java.lang.String getCaption()
	{
		return com.mendix.core.Core.getInternationalizedString("en_US", i18nCaptionKey);
	}
}
