// This file was generated by Mendix Studio Pro.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package nativemobileresources.proxies;

public enum InAppBrowserDismissButtonStyle
{
	done("13bdae5b-ec61-4346-b922-ee38302f16a4"),
	close("6158fea3-8a77-4262-af31-134566d51074"),
	cancel("62e4e223-c9ef-4799-aee1-2a05c231f5b2");

	private final java.lang.String i18nCaptionKey;
	
	private InAppBrowserDismissButtonStyle(java.lang.String i18nCaptionKey)
	{
		this.i18nCaptionKey = i18nCaptionKey;
	}

	public java.lang.String getCaption(java.lang.String languageCode)
	{
		String caption = com.mendix.core.Core.getInternationalizedString(languageCode, i18nCaptionKey);
		return caption.isEmpty() ? getCaption() : caption;
	}

	public java.lang.String getCaption()
	{
		return com.mendix.core.Core.getInternationalizedString("en_US", i18nCaptionKey);
	}
}
