// This file was generated by Mendix Studio Pro.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package nativemobileresources.proxies;

public enum PictureQuality
{
	original("516e0d7d-e007-43fa-880e-b6472601ba2f"),
	low("c2f5d64a-31bb-4d86-8b36-a82b685bfe4c"),
	medium("ffda8bec-5a4b-45e4-93c4-472b4bc288cc"),
	high("0d1613b2-32f0-4548-b159-34fb8ccc46e9"),
	custom("63bf5bff-13ec-477d-bb79-cd69a59f2e98");

	private final java.lang.String i18nCaptionKey;
	
	private PictureQuality(java.lang.String i18nCaptionKey)
	{
		this.i18nCaptionKey = i18nCaptionKey;
	}

	public java.lang.String getCaption(java.lang.String languageCode)
	{
		String caption = com.mendix.core.Core.getInternationalizedString(languageCode, i18nCaptionKey);
		return caption.isEmpty() ? getCaption() : caption;
	}

	public java.lang.String getCaption()
	{
		return com.mendix.core.Core.getInternationalizedString("en_US", i18nCaptionKey);
	}
}
