// This file was generated by Mendix Studio Pro.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package nativemobileresources.proxies;

public enum PictureQuality
{
	original("ec243dcf-d4c6-427b-bb70-ed452534b3c6"),
	low("11a2ca59-0ae2-46ca-9f24-7018b143f986"),
	medium("570dbc0a-23d0-42e7-a1f3-5e5c8a290b67"),
	high("1626178b-6921-47eb-829f-710c9d8cbd9b"),
	custom("d20096eb-2039-4ce2-b72a-b253a3d8fcc5");

	private final java.lang.String i18nCaptionKey;
	
	private PictureQuality(java.lang.String i18nCaptionKey)
	{
		this.i18nCaptionKey = i18nCaptionKey;
	}

	public java.lang.String getCaption(java.lang.String languageCode)
	{
		String caption = com.mendix.core.Core.getInternationalizedString(languageCode, i18nCaptionKey);
		return caption.isEmpty() ? getCaption() : caption;
	}

	public java.lang.String getCaption()
	{
		return com.mendix.core.Core.getInternationalizedString("en_US", i18nCaptionKey);
	}
}
