// This file was generated by Mendix Studio Pro.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package nativemobileresources.proxies;

public enum StatusBarHideShowAnimation
{
	none("1a14867e-5b75-456a-b7b6-50da13c39761"),
	fade("6871ce33-b82e-457f-b754-63367e1415d2"),
	slide("139a3a1f-3af1-48aa-a21a-fb3fd212b0e6");

	private final java.lang.String i18nCaptionKey;
	
	private StatusBarHideShowAnimation(java.lang.String i18nCaptionKey)
	{
		this.i18nCaptionKey = i18nCaptionKey;
	}

	public java.lang.String getCaption(java.lang.String languageCode)
	{
		String caption = com.mendix.core.Core.getInternationalizedString(languageCode, i18nCaptionKey);
		return caption.isEmpty() ? getCaption() : caption;
	}

	public java.lang.String getCaption()
	{
		return com.mendix.core.Core.getInternationalizedString("en_US", i18nCaptionKey);
	}
}
